title:               GitHub Blog
description:         --Wenqi Li
show_downloads:      false
google_analytics:
theme:               jekyll-theme-cayman

# Setup
baseurl:             https://firelands128.github.io

# Custom vars
version:             1.0.0
