title:               GitHub Blog
description:         --Wenqi Li
show_github:         true
show_downloads:      false
google_analytics:
theme:               jekyll-theme-cayman

# Custom vars
version:             1.0.0
