title:               GitHub Blog
description:         --Wenqi Li
show_downloads:      false
google_analytics:
theme:               jekyll-theme-cayman

# Setup
baseurl:             https://firelands128.github.io

# About/contact
author:
  name:              Wenqi Li
  url:               https://firelands128.github.io
  email:             firelands128@gmail.com

# Custom vars
version:             1.0.0
